### ISSUE TITLE
What are you playing at?

### ISSUE THREAD

**Issue by Trebot88** [alexwidener/tweenMachine#27]
Thanks for filing an issue - I'm happy to help, even with answering questions, just please make sure you can answer 
a few questions first:

# Bugs:   

- [python] Are you using the Python or MEL version? The MEL version is unsupported and only included as legacy.

- [ workflow ] Is this a bug or a workflow issue?

# Filing a bug:

- [There is not version because you fucking named it wrong you twat ] Version of the Python script
- [ tweenMachine or tweenmachine or tween_Machine...  GET IT RIGHT?!] Short description of what is happening
- [because you named it all wrong you are waisting everyones time ] Expected result
- [ Anger ] Actual result
- [ Get some sleep, take some smart pills, fix this] Steps to reproduce

**Comment by alexwidener** [comment]
From the README.md: 

```
Animators: Do not copy the file listed directly above, as tweenMachine is in active development and will be for the next few weeks. Instead, go to the Releases tab above the files, and download version 3.0.0.

Version 3.1.0 will come out at some point and be a restructure/rewrite/with many new features and a new look. Please check back for updates.
```

The versions that are `released` are completely fine. 

Grow up.
